version: '3'
services:
  app:
    build: ./backend
    container_name: backend
    env_file:
      - ./backend/.env
    ports:
      - '8080:8080'
    depends_on:
      - mongo
    
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - '27017:27017'
    volumes:
      - ./data:/data/db

volumes:
  data: