version: "3.8"

services:
  frontend:
    image: izimio/kdb-ui:taker-academy-ui-1.0.0
    ports:
      - "3000:3000"

  backend:
    build: backend
    environment:
      MONGODB_URI: ${MONGODB_URI}
      JWT_SECRET: ${JWT_SECRET}
    depends_on:
      - mongo

  mongo:
    image: mongo:latest

networks:
  my-network:
    external: true